### ISSUE TITLE
Socket options subtyping issue

### ISSUE THREAD

**Issue by Cjen1** [issuu/ocaml-zmq#100]
I'm trying to write the following code:

```
let socket : [`Router] Zmq.Socket.t = Zmq.Socket.create context Zmq.Socket.router in
Zmq.Socket.set_probe_router socket true;
```
However I am getting an error 
```
This expression has type [ `Router ] Zmq.Socket.t but an expression was expected of type [> `Dealer | `Req | `Router ] Zmq.Socket.t The first variant type does not allow tag(s) `Dealer, `Req
```
My understanding is that this is due to the typing restriction on `set_probe_router`.

However checking the equivalent of this in utop 
```
type 'a box = Box of 'a

let (x : `A box ) = Box `A
let f : [`A | `B] box -> unit = fun b -> ()
```

`f x` fails with the same error, however
`f (x :> ['A | 'B] box)` works as expected.

Attempting a similar approach above however fails stating that 
```Type [ `Router ] Zmq.Socket.t is not a subtype of [ `Dealer | `Req | `Router ] Zmq.Socket.t```

This is ocaml 4.08.0 that this occurs.

**Comment by Cjen1** [comment]
And also 4.08.1

**Comment by andersfugmann** [comment]
Is there any reason that you need to explicitly annotate the type of the socket in the let binding?
Would it not be easier either to remove the explicit type annotation, or change the type annotation to:

```ocaml
let socket : [>`Router] Zmq.Socket.t = Zmq.Socket.create context Zmq.Socket.router in
```
