### ISSUE TITLE
Error while building with OCaml 5.0

### ISSUE THREAD

**Issue by davisuga** [issuu/ocaml-zmq#119]
I get the following error while running `opam install zmq` with ocaml 5.0.0+trunk:
```
The following actions will be performed:
  ∗ install zmq 5.1.5

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⬇ retrieved zmq.5.1.5  (cached)
[ERROR] The compilation of zmq.5.1.5 failed at "dune build -p zmq -j 7 @install".

#=== ERROR while compiling zmq.5.1.5 ==========================================#
# context     2.1.0 | linux/x86_64 | ocaml-variants.5.0.0+trunk | https://opam.ocaml.org#a6d8661d
# path        ~/.opam/5.0.0+trunk/.opam-switch/build/zmq.5.1.5
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p zmq -j 7 @install
# exit-code   1
# env-file    ~/.opam/log/zmq-201580-b9972a.env
# output-file ~/.opam/log/zmq-201580-b9972a.out
### output ###
# File "zmq/src/dune", line 15, characters 24-32:
# 15 |  (libraries unix stdint bigarray))
#                              ^^^^^^^^
# Error: Library "bigarray" not found.
# -> required by library "zmq" in _build/default/zmq/src
# -> required by _build/default/META.zmq
# -> required by _build/install/default/lib/zmq/META
# -> required by _build/default/zmq.install
# -> required by alias install



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build zmq 5.1.5
└─ 
╶─ No changes have been performed
```
I think that this error is happening because [the bigarray library was removed](https://github.com/ocaml/ocaml/pull/10896) and it is now part of the standard library.

**Comment by andersfugmann** [comment]
I have not tested against 5.0.0 trunk, but as `StdInt` package requires ocaml < 5.0.0 the zmq package cannot be installed. 
I do not know why compilation complains about missing `bigarray` though. 

I've created #121 to remove dependency on `StdInt`, and added testing against `ocaml 5.0.0~beta1` with can compile (and run tests) successfully. 

Is the problem present for you on ocaml 5.0.0~beta1 aswell?

**Comment by andersfugmann** [comment]
Did you manage to re-test?
The PR to remove dependency on StdInt has been merged which allows building on ocaml 5.0.0. I'm planning a new release later this week, so it would be great to understand if you are able to compile ocaml-zmq on ocaml 5.0.0.

**Comment by davisuga** [comment]
Yes, it is working fine in the 5.0.0~beta1.

**Comment by andersfugmann** [comment]
Awesome. Thanks for verifying!
