### ISSUE TITLE
Package should not use oasis at install time

### ISSUE THREAD

**Issue by whitequark** [issuu/ocaml-zmq#23]
Using OASIS at install time is an antipattern, because the version of OASIS the user has does not necessarily match the one developer had. In practice, this leads to this bug: http://pastebin.com/PL4DqnRV. Key part: `-ccopt '${pkg_uint_uint64}'` is not expanded.

What you should do instead is to make a branch for every release, do `oasis setup`, commit the resulting generated files, and tag the commit. This is what pretty much all projects that use OASIS with github do.

**Comment by andersfugmann** [comment]
Ive included oasis generated files in the latest release, as oasis seems not to be working for ocaml 4.03 (flambda)
