### ISSUE TITLE
I am not sure it is wise to have variant types

### ISSUE THREAD

**Issue by UnixJunkie** [issuu/ocaml-zmq#25]
I get this kind of errors:
[...]  contains type variables that cannot be generalized
And even if I explicitely type my function:

    let zmq_server_setup (host: string) (port: int):
      ZMQ.Context.t * ([> `Rep] ZMQ.Socket.t) = [...]

I cannot get completely rid of those errors.
Was it absolutely necessary to use variants to write the zmq bindings?

**Comment by whitequark** [comment]
Use <code>[`Rep]</code> for return values.

**Comment by UnixJunkie** [comment]
Oh yes, sorry, I didn't know that. Thanks!
