### ISSUE TITLE
does not compile on mac

### ISSUE THREAD

**Issue by UnixJunkie** [issuu/ocaml-zmq#33]
https://gist.github.com/UnixJunkie/8d62a75a4558b23ad6a7

**Comment by jj-issuu** [comment]
It works for me on Mac OS 10.10. Have you done `brew install zeromq` so that `/usr/local/include/zmq.h` exists?

**Comment by jj-issuu** [comment]
I'm getting this problem too after upgrading to Mac OS 10.11 (El Capitan). The default search path for clang has changed so it no longer contains /usr/local/include. Fixing this should also fix #34.

**Comment by UnixJunkie** [comment]
That would be nice !

**Comment by jj-issuu** [comment]
Options for fixing this:
- Commit OASIS auto-generated files plus modifications suggested in #34 (would also close #34 and #23).
- Add /usr/local/include and /usr/local/lib to compiler search paths (just merge PR #34).
- Add /usr/local/... only on `os_type(Unix)` and possibly `system(macosx)` and FreeBSD (would also close #34).
- Make the _oasis file be auto-generated based on output of pkg-config. I don't think anybody feels that OASIS needs one more level of auto-generated files.

Whatever fix we choose, I'd also like to submit the same fix to https://github.com/savonet/ocaml-ssl, which has the same problem on El Capitan.

**Comment by UnixJunkie** [comment]
As ugly as it might seem, some people do commit the OASIS auto-generated files since
it makes users of the software not need oasis anymore.

**Comment by UnixJunkie** [comment]
So, no fix still ?

**Comment by jj-issuu** [comment]
This was fixed in release 4.0-5, which appeared on opam about a week ago. I ended up using the simplest possible fix: merging PR #34, which added /usr/local/bin and /usr/local/lib to the compiler paths.

**Comment by UnixJunkie** [comment]
Nice, thanks !
