### ISSUE TITLE
Release 5.0.0

### ISSUE THREAD

**Issue by andersfugmann** [issuu/ocaml-zmq#55]
We should make a new release soon with all the changes going in.
 For that we need to decide what needs to go in (e.g. Should we wait for zmq-lwt?) 
This ticket if for coordinating the release (when, what  and who makes the PR against opam-repository).

Also I think we should have a Changelog file to list changes between releases, and we might need to consider a better version scheme.

**Comment by Leonidas-from-XIV** [comment]
I talked to @rgrinberg yesterday when the Lwt backend is planned for inclusion and he said sometime next week, so I think we should be able to wait as long, especially as the other OPAM packages can then be replaced by this one in one go.

**Comment by andersfugmann** [comment]
Ok. Lets schedule a release after #54 is done.

**Comment by hcarty** [comment]
I'd also like to get the bigarray versions of `*_all` in along with async/lwt interfaces to those functions.

**Comment by andersfugmann** [comment]
I think the last remaining things has been addressed, so we should prepare a release.
Remaining is:
 * Wait for #65? 
 * Determine a version number. All ideas are welcome. 
 * Select a volunteer to create a PR against opam-repository.
   (And create a suitable descr)
 * Announce the release to ocaml-discuss

**Comment by rgrinberg** [comment]
Anders Peter Fugmann <notifications@github.com> writes:

>  * Wait for #65? 

I don't think it's necesasry as the change would be backwards compatible
anyways.

>  * Select a volunteer to create a PR against opam-repository.
>    (And create a suitable descr)

Ah yes, we also need to .descr files into the repo (will do so now)

>  * Announce the release to ocaml-discuss 

and caml-list

**Comment by rgrinberg** [comment]
Anders Peter Fugmann <notifications@github.com> writes:

>  * Select a volunteer to create a PR against opam-repository.
>    (And create a suitable descr)

Is there any interest in using topkg/opam publish to do the release
submissions? Those simplify the process of making relases greatly. I can
help set this up if you don't have experience with it.

**Comment by hcarty** [comment]
topkg/opam publish both seem like good ideas. I haven't ever used them properly as the last time I tried I couldn't get past an issue with the tooling + github's 2fa. Thinga may have been improved since then.

**Comment by andersfugmann** [comment]
Automated release to opam repository through a make target would be really nice.

**Comment by andersfugmann** [comment]
We should create a new release. Any opinions on a version number?
I happily do the PR against the opam repository once we settle for a version number.

**Comment by rgrinberg** [comment]
A major version bump seems appropriate to me.

**Comment by hcarty** [comment]
I like 5.0.0 for this next release as well.

Quick bikeshedding question - should `ZMQ.Msg.data` be renamed to `ZMQ.Msg.bigstring` since that's what the rest of the OCaml world calls it?  I can make a quick PR with the rename if you agree.

**Comment by hcarty** [comment]
Also, should `ZMQ` vs `Zmq` as a module name be addressed at the same time?

**Comment by Leonidas-from-XIV** [comment]
I recently tried `topkg`(`-care`) with its `jbuilder` integration and while not perfect think it could be a useful tool to create tags, write changelog entries, upload API documentation, create release tarballs and maybe submit OPAM PRs. At least until `dune-release` is ready.

If there is interest for it I can make a PR to add the necessary boilerplate, then it can be done to automate the tedious & repetitive parts of releasing.

**Comment by andersfugmann** [comment]
@hcarty As much as I would like to change the name from ZMQ to Zmq, it would break backward compatibility so I'm a bit hesitant.  Perhaps we could create a deprecated module ZMQ that includes Zmq?.

**Comment by andersfugmann** [comment]
@hcarty Will you create a PR for ZMQ -> Zmq? 
I'm fine by switching to semantic versioning. I assume that 5.0.0 > 4.0-8

**Comment by hcarty** [comment]
I'll prepare the ZMQ -> Zmq PR

**Comment by hcarty** [comment]
PR in as #74

**Comment by Leonidas-from-XIV** [comment]
It seems to me everything is in place to release 5.0.0. 🙌

**Comment by andersfugmann** [comment]
One merged, Ill post an announcement on ocaml-discuss and close this Ticket. 
Thanks all for the work! Beers on me.

**Comment by andersfugmann** [comment]
Oh. Revdeps is defiantly going to fail:

* async-zmq <= zmq
* lwt-zmq  <= zmq
* jupyter <= zmq
* jupyter-kernel <= lwt-zmq <= zmq

For these packages zmq should be restricted to `zmq < 5.0.0`.
@rgrinberg Should I prepare a PR for opam repository to restrict the zmq version for all revisions of the packages?

**Comment by hcarty** [comment]
Merged!

**Comment by hcarty** [comment]
Thanks for putting the PR together

**Comment by andersfugmann** [comment]
Announcement is out. Closing.
