### ISSUE TITLE
Generate documentation

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [issuu/ocaml-zmq#59]
It would be good to automatically generate API documentation on https://issuu.github.io/ocaml-zmq. I am not sure what the best way for doing so is now in 2018, so I'd very much appreciate input on what to check out. The best way would be if it could be somehow automatically split into `master` vs release tags.

My main priority would be that it can be somehow automated so it is not easy to forget.

**Comment by rgrinberg** [comment]
`$ jbuilder build @doc` works if you have odoc. However, things aren't completely ideal at the moment as attaching your mld's isn't as straightforward as I'd like.

**Comment by hcarty** [comment]
We could use something like [this](https://github.com/hcarty/ocaml-project-templates/blob/700e623d9da72dbb54289896384ac3611d656d1d/library/Makefile#L22-L32) which is roughly based on what cohttp used to use.  It'll generate and push the documentation.  It may not be perfect but it will provide an odoc-rendered version for users to refer to.

**Comment by hcarty** [comment]
#60 contains a `make` target to generate and push out odoc-generated documentation.

**Comment by andersfugmann** [comment]
@simonellefsen , can you help in enabling gh-pages for the ocaml-zmq project?
(https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages)

**Comment by hcarty** [comment]
Is there anything the rest of us can do to help with this?

**Comment by simonellefsen** [comment]
gh-pages is already enabled according to the setting - so not sure what to do next
![screen shot 2018-03-21 at 11 36 38](https://user-images.githubusercontent.com/647118/37705454-5d515c14-2cfc-11e8-862e-dedc65f3e9a0.png)

**Comment by andersfugmann** [comment]
That's very strange - I would have expected that to work. Thanks anyways.

**Comment by andersfugmann** [comment]
I wrote github support, and they have fixed the problem. For some reason the site had not been build, so they triggered a build manually. It works now:  https://issuu.github.io/ocaml-zmq

**Comment by andersfugmann** [comment]
I took the liberty to update the documentation. We should add a link from the readme file.

**Comment by hcarty** [comment]
It may also be worth adding a link from the project description - that way there's an immediate path to both the upstream library and the binding documentation.

**Comment by andersfugmann** [comment]
#73 adds links to the documentation. Closing
