### ISSUE TITLE
[opam] "Homepage" link is 404 (github/pdhborges/...)

### ISSUE THREAD

**Issue by softmoth** [issuu/ocaml-zmq#81]
The `Homepage` link on http://opam.ocaml.org/packages/ocaml-zmq/ is broken. It points to an old GitHub repo.

**Comment by hcarty** [comment]
That's a different binding to zeromq. The core library from this repo is here on the opam site: http://opam.ocaml.org/packages/zmq/

**Comment by softmoth** [comment]
Thanks, I'll open an issue on opam-repository to suggest either removing it or mentioning that this package is out of date and recommending the current one.
