### ISSUE TITLE
Should also depend on conf-libsodium?

### ISSUE THREAD

**Issue by copy** [issuu/ocaml-zmq#82]
At least when compiling statically, it seems to be necessary:

```
/usr/lib/gcc/x86_64-alpine-linux-musl/6.4.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lsodium
```

`opam depext --install conf-libsodium` makes it go away.

**Comment by hcarty** [comment]
A downside to this is that zeromq can be built without libsodium. Both by building it without encrypted communication support and by using the built-in tweetnacl.

**Comment by copy** [comment]
> A downside to this is that zeromq can be built without libsodium. Both by building it without encrypted communication support and by using the built-in tweetnacl.

That makes, I think it's fine to close this issue.
